//! A synthetic Image Lab `.scn` built from the layout in `docs/formats/biorad-scn.md` (Image Lab
//! style: a plain delimiter after every part, no `--B--` closing marker): image size, pixel
//! size, channel, pixels, audit log and experiment facts; truncations fail cleanly.

use openreadout_core::source::Input;
use openreadout_core::{Dataset, FormatReader, PlaneIndex};
use openreadout_gel::ImageLabReader;

fn part(boundary: &str, desc: &str, ctype: &str, body: &[u8]) -> Vec<u8> {
    let mut p = format!(
        "--{boundary}\r\nContent-Type: {ctype}\r\nContent-Length: {}\r\nContent-Description: {desc}\r\nX-EntityRank: middle\r\n\r\n",
        body.len()
    )
    .into_bytes();
    p.extend_from_slice(body);
    p
}

fn scn(width: u32, height: u32) -> Vec<u8> {
    let outer = "20240101-120000-0xAAAA";
    let inner = "20240101-120000-0xBBBB";
    let item = "<!DOCTYPE XML>\n<root version=\"2\">\n <FileAuthoringInfo>\n  <version>6.1.0.7</version>\n </FileAuthoringInfo>\n <name>blot 1</name>\n <user>Ada</user>\n <channel_count>1</channel_count>\n</root>\n";
    let header = format!(
        "<!DOCTYPE XML>\n<root>\n <name></name>\n <creation_date>1704110400</creation_date>\n <endian>little</endian>\n <size_pix height=\"{height}\" width=\"{width}\"/>\n <org_size_pix height=\"{height}\" width=\"{width}\"/>\n <size_mm known=\"true\" height=\"{}\" width=\"{}\"/>\n <scanner data_ceiling=\"65535\" max_value=\"65535\"/>\n <image zero_is=\"white\"/>\n <scan_attributes>\n  <imager type=\"0\" name=\"Imager\" value=\"ChemiDoc™ MP\"/>\n  <image_date type=\"3\" name=\"Image Date\" value=\"2024-01-01T12:00:00\"/>\n  <exposure_time type=\"1\" name=\"Exposure Time (sec)\" value=\"2.5\"/>\n  <serial_number type=\"0\" name=\"Serial Number\" value=\"734BR-0001\"/>\n  <application type=\"0\" name=\"Application\" value=\"IRDye 800CW\"/>\n  <emission_filter type=\"0\" name=\"Emission Filter\" value=\"835/50 Filter\"/>\n </scan_attributes>\n <units>Int</units>\n</root>\n",
        f64::from(height) * 0.1,
        f64::from(width) * 0.1
    );
    let protocol = "<!DOCTYPE XML>\n<root version=\"2\">\n <protocol_settings>\n  <exposure_time>2.5</exposure_time>\n </protocol_settings>\n <ListLogEntries>\n  <LogEntry>\n   <Timestamp>1704110500</Timestamp>\n   <FullName>Ada Lovelace</FullName>\n   <Data>Image rotated 1.05 degrees.</Data>\n  </LogEntry>\n </ListLogEntries>\n</root>\n";
    let pixels: Vec<u8> = (0..width * height)
        .flat_map(|i| u16::try_from(i % 65536).unwrap().to_le_bytes())
        .collect();
    let mut nested = part(inner, "ImageData", "application/octet-stream", &pixels);
    nested.extend(part(
        inner,
        "ImageHeader",
        "text/xml; charset=\"utf8\"",
        header.as_bytes(),
    ));
    nested.extend(format!("--{inner}\r\n").into_bytes());
    let mut f = format!(
        "MIME-Version: 1.0 (Generated by Image Lab 6.1.0)\r\nContent-Type: multipart/mixed; boundary=\"{outer}\"\r\nContent-Description: Image Lab Image File\r\n\r\n"
    )
    .into_bytes();
    f.extend(part(
        outer,
        "ItemHeaderTag",
        "text/xml; charset=\"utf8\"",
        item.as_bytes(),
    ));
    f.extend(
        format!(
            "--{outer}\r\nContent-Type: multipart/mixed; boundary=\"{inner}\"\r\nContent-Description: ScanImageTag0\r\n\r\n"
        )
        .into_bytes(),
    );
    f.extend(nested);
    f.extend(part(
        outer,
        "ItemProtocolSettingsTag",
        "text/xml; charset=\"utf8\"",
        protocol.as_bytes(),
    ));
    f.extend(format!("--{outer}\r\n").into_bytes());
    f
}

fn open(bytes: Vec<u8>) -> openreadout_core::Result<Box<dyn Dataset>> {
    ImageLabReader.open_input(&Input::from_bytes("blot.scn", bytes))
}

#[test]
fn image_metadata_pixels_and_log() {
    let bytes = scn(20, 10);
    assert!(
        ImageLabReader
            .sniff(&bytes, std::path::Path::new("blot.scn"))
            .is_some()
    );
    let mut ds = open(bytes).unwrap();
    let info = ds.info().unwrap();
    assert_eq!(info.format.id, "biorad-scn");
    assert_eq!(info.format_version.as_deref(), Some("Image Lab 6.1.0"));
    let im = &info.images[0];
    assert_eq!((im.size_x, im.size_y), (20, 10));
    assert!((im.physical_size.x.unwrap() - 100.0).abs() < 1e-9);
    assert_eq!(im.channels[0].name.as_deref(), Some("IRDye 800CW"));
    assert_eq!(im.channels[0].exposure_ms, Some(2500.0));
    assert_eq!(im.channels[0].emission_nm, Some(835.0));
    assert_eq!(im.extra["display_inverted"], true);
    let p = ds.read_plane(0, PlaneIndex::default()).unwrap();
    assert_eq!(p.data.len(), 400);
    assert_eq!(u16::from_le_bytes([p.data[398], p.data[399]]), 199);
    assert_eq!(info.tables[0].name.as_deref(), Some("log"));
    let log = ds.read_table(0, 0, 10).unwrap();
    assert_eq!(log.columns[0], vec![1_704_110_500.0]);
    let e = ds.experiment().unwrap();
    assert_eq!(
        e.instrument.as_ref().unwrap().model.as_deref(),
        Some("ChemiDoc MP")
    );
    assert_eq!(
        e.instrument.as_ref().unwrap().software_version.as_deref(),
        Some("6.1.0.7")
    );
    assert_eq!(
        e.acquisition.as_ref().unwrap().operator.as_deref(),
        Some("Ada")
    );
    assert_eq!(
        e.measurements[0].technique.as_ref().unwrap().id,
        "OBI:0000854"
    );
    assert!(ds.check().unwrap().ok);
    assert!(ds.read_plane(1, PlaneIndex::default()).is_err());
}

#[test]
fn damage_is_clean() {
    let good = scn(16, 8);
    for cut in (0..good.len()).step_by(37) {
        if let Ok(mut ds) = open(good[..cut].to_vec()) {
            let _ = ds.info();
            let _ = ds.check();
            let _ = ds.read_plane(0, PlaneIndex::default());
        }
    }
    // image data that does not match width × height: the scan is refused, the file still opens
    let bad =
        String::from_utf8_lossy(&good).replace("width=\"16\"/>\n <org", "width=\"17\"/>\n <org");
    let mut ds = open(bad.into_bytes()).unwrap();
    assert!(ds.info().unwrap().images.is_empty());
    assert!(!ds.check().unwrap().ok);
    // not an Image Lab file
    assert!(open(b"MIME-Version: 1.0\r\nContent-Type: text/plain\r\n\r\nhello".to_vec()).is_err());
}
