"""Type stubs for the compiled extension. Use the public wrappers in :mod:`openreadout`."""

from typing import Any, List, Optional, Tuple

import numpy as np
from numpy.typing import NDArray

__version__: str

class NativeFile:
    @property
    def path(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def info_json(self) -> str: ...
    def full_json(self, vendor: bool) -> str: ...
    def explain_json(self, ask: Optional[str] = None) -> str: ...
    def analyze_json(self, kind: str, options: str) -> str: ...
    def vendor_json(self) -> str: ...
    def well_stats_json(
        self, select: list[str] = ..., wells: list[str] = ..., per_field: bool = ...
    ) -> str: ...
    def stats_json(
        self,
        image: int | None = ...,
        select: list[str] = ...,
        level: int = ...,
        region: tuple[int, int, int, int] | None = ...,
        bins: int = ...,
        log_bins: bool = ...,
        per_plane: bool = ...,
        mip: str | None = ...,
    ) -> str: ...
    def provenance_json(self) -> str: ...
    def entries_json(self) -> str: ...
    def check_json(self) -> str: ...
    def ome_xml(self) -> str: ...
    @property
    def handle_count(self) -> int: ...
    def set_transient(self, on: bool) -> None: ...
    def read_plane(
        self,
        image: int,
        c: int,
        z: int,
        t: int,
        level: int = 0,
        region: Optional[Tuple[int, int, int, int]] = None,
    ) -> Tuple[int, int, int, str, NDArray[np.uint8]]: ...
    def read_table(
        self, table: int = 0, first_row: int = 0, max_rows: Optional[int] = None
    ) -> Tuple[int, int, NDArray[np.float64]]: ...
    def read_spectrum_scan(
        self, run: int, scan: int, centroid: bool = False
    ) -> Tuple[str, NDArray[np.float64], NDArray[np.float32]]: ...
    def scans_json(self, run: int, filter: str, offset: int = 0, limit: int = ...) -> str: ...
    def read_trace(
        self,
        trace: int = 0,
        sweep: int = 0,
        first_sample: int = 0,
        max_samples: Optional[int] = None,
    ) -> Tuple[int, int, NDArray[np.float64]]: ...
    def export_ome_tiff(
        self,
        output: str,
        image: Optional[int] = None,
        select: Optional[List[str]] = None,
        compression: str = "deflate",
        overwrite: bool = False,
        embed_vendor: bool = False,
        level: int = 0,
        region: Optional[Tuple[int, int, int, int]] = None,
        pyramid: str = "auto",
        levels: Optional[int] = None,
        tile: int = 512,
    ) -> str: ...
    def export_ome_zarr(
        self,
        output: str,
        image: Optional[int] = None,
        select: Optional[List[str]] = None,
        compression: str = "deflate",
        overwrite: bool = False,
        embed_vendor: bool = False,
        level: int = 0,
        region: Optional[Tuple[int, int, int, int]] = None,
        pyramid: str = "auto",
        levels: Optional[int] = None,
        chunk: int = 512,
    ) -> str: ...
    def read_spectrum(
        self, run: int, index: int, centroid: bool = False
    ) -> Tuple[str, NDArray[np.float64], NDArray[np.float32]]: ...
    def to_arrow(
        self,
        table: Optional[int],
        trace: Optional[int],
        sweep: Optional[int],
        first_row: Optional[int],
        last_row: Optional[int],
        spectra: bool,
        run: int,
        centroid: bool,
        per_scan: bool,
        max_rows: Optional[int],
    ) -> Any: ...
    def export_mzml(
        self, output: str, run: int = 0, centroid: bool = False, overwrite: bool = False
    ) -> str: ...

def open(path: str) -> NativeFile: ...
def open_bytes(data: bytes, name: str) -> NativeFile: ...
def open_fileobj(fileobj: Any, name: str, size: Optional[int] = None) -> NativeFile: ...
def detect_json(path: str) -> str: ...
def detect_bytes_json(data: bytes, name: str) -> str: ...
def detect_fileobj_json(fileobj: Any, name: str, size: Optional[int] = None) -> str: ...
def formats_json() -> str: ...
def analyze_json(path: str, kind: str, options: str) -> Tuple[str, Optional[bytes]]: ...
def export_rdml_json(path: str, output: Optional[str] = None, overwrite: bool = False) -> str: ...
def batch_json(request_json: str) -> str: ...
def summarize_json(request_json: str) -> str: ...
def link_json(request_json: str) -> str: ...
