//! Assurance profiles (`docs/assurance.md`) of the electrochemistry readers: the variant features
//! of a file and the feature values the development corpus validates. The tables between the
//! GENERATED markers are written by `cargo xtask assurance-audit --write`.

use openreadout_core::FileInfo;
use openreadout_core::assurance::{
    self as a, AssuranceProfile, Basis, FeatureKind as K, Observations, Scope, Validated,
};
use openreadout_core::provenance::Confidence;

pub(crate) static BIOLOGIC_MPR: AssuranceProfile = AssuranceProfile {
    format_id: "biologic-mpr",
    observe,
    validated: BIOLOGIC_MPR_VALIDATED,
    confidence: BIOLOGIC_MPR_CONFIDENCE,
    basis: Basis::ReverseEngineered,
};

pub(crate) static BIOLOGIC_MPT: AssuranceProfile = AssuranceProfile {
    format_id: "biologic-mpt",
    observe,
    validated: BIOLOGIC_MPT_VALIDATED,
    confidence: BIOLOGIC_MPT_CONFIDENCE,
    basis: Basis::ReverseEngineered,
};

pub(crate) static GAMRY_DTA: AssuranceProfile = AssuranceProfile {
    format_id: "gamry-dta",
    observe,
    validated: GAMRY_DTA_VALIDATED,
    confidence: GAMRY_DTA_CONFIDENCE,
    basis: Basis::PriorArt,
};

pub(crate) static NEWARE_NDA: AssuranceProfile = AssuranceProfile {
    format_id: "neware-nda",
    observe,
    validated: NEWARE_NDA_VALIDATED,
    confidence: NEWARE_NDA_CONFIDENCE,
    basis: Basis::PriorArt,
};

pub(crate) static NEWARE_NDAX: AssuranceProfile = AssuranceProfile {
    format_id: "neware-ndax",
    observe,
    validated: NEWARE_NDAX_VALIDATED,
    confidence: NEWARE_NDAX_CONFIDENCE,
    basis: Basis::PriorArt,
};

pub(crate) static ARBIN_RES: AssuranceProfile = AssuranceProfile {
    format_id: "arbin-res",
    observe,
    validated: ARBIN_RES_VALIDATED,
    confidence: ARBIN_RES_CONFIDENCE,
    basis: Basis::PriorArt,
};

fn observe(info: &FileInfo) -> Observations {
    let mut o = Observations::default();
    if let Some(v) = &info.format_version {
        o.feature(K::FormatVersion, v, &[Scope::Metadata, Scope::Traces]);
    }
    // A text export's columns are all read by the same number parser, so a column no
    // development file had describes the file; in a binary file its id decides how its bytes
    // are decoded.
    let text = matches!(info.format.id.as_str(), "biologic-mpt" | "gamry-dta");
    for t in &info.traces {
        for c in &t.channels {
            if c.name == "time" {
                continue;
            }
            let value = format!("column {}", c.name);
            if text {
                o.context(K::Record, value);
            } else {
                o.feature(K::Record, value, &[Scope::Traces]);
            }
        }
    }
    o
}

// BEGIN GENERATED biologic-mpr (cargo xtask assurance-audit --write; do not edit)
const BIOLOGIC_MPR_CONFIDENCE: Confidence = Confidence::High;
#[rustfmt::skip]
const BIOLOGIC_MPR_VALIDATED: &[Validated] = &[
    a::row(K::Acquisition, "Battery Capacity Determination", 1, 1, 1),
    a::row(K::Acquisition, "Chronoamperometry / Chronocoulometry", 2, 2, 2),
    a::row(K::Acquisition, "Chronopotentiometry", 1, 1, 1),
    a::row(K::Acquisition, "Constant Current", 1, 1, 1),
    a::row(K::Acquisition, "Cyclic Voltammetry", 2, 2, 2),
    a::row(K::Acquisition, "Cyclic Voltammetry Advanced", 1, 1, 1),
    a::row(K::Acquisition, "Galvano Electrochemical Impedance Spectroscopy", 1, 1, 1),
    a::row(K::Acquisition, "Galvanostatic Cycling with Potential Limitation", 2, 1, 2),
    a::row(K::Acquisition, "IR compensation (PEIS)", 1, 1, 1),
    a::row(K::Acquisition, "Linear Sweep Voltammetry", 1, 1, 1),
    a::row(K::Acquisition, "Modulo Bat", 2, 1, 2),
    a::row(K::Acquisition, "Open Circuit Voltage", 4, 3, 4),
    a::row(K::Acquisition, "Potentio Electrochemical Impedance Spectroscopy", 2, 1, 2),
    a::row(K::Field, "experiment.acquisition.started_at", 19, 5, 19),
    a::row(K::FormatVersion, "data module 11", 9, 3, 9),
    a::row(K::FormatVersion, "data module 2", 2, 1, 2),
    a::row(K::FormatVersion, "data module 3", 10, 3, 10),
    a::row(K::FormatVersion, "mpr data module 11", 9, 3, 9),
    a::row(K::FormatVersion, "mpr data module 2", 2, 1, 2),
    a::row(K::FormatVersion, "mpr data module 3", 10, 3, 10),
    a::row(K::Record, "column analog_in_1", 2, 2, 2),
    a::row(K::Record, "column analog_in_2", 2, 2, 2),
    a::row(K::Record, "column capacitance_charge", 3, 1, 3),
    a::row(K::Record, "column capacitance_discharge", 3, 1, 3),
    a::row(K::Record, "column capacitance_parallel", 3, 1, 3),
    a::row(K::Record, "column capacitance_series", 3, 1, 3),
    a::row(K::Record, "column charge", 9, 1, 9),
    a::row(K::Record, "column charge_coulomb", 7, 3, 7),
    a::row(K::Record, "column charge_half_cycle", 9, 2, 9),
    a::row(K::Record, "column control", 4, 1, 4),
    a::row(K::Record, "column control_changes", 13, 3, 13),
    a::row(K::Record, "column control_current", 3, 1, 3),
    a::row(K::Record, "column control_potential", 6, 3, 6),
    a::row(K::Record, "column counter_increment", 11, 3, 11),
    a::row(K::Record, "column current", 5, 1, 5),
    a::row(K::Record, "column current_amplitude", 4, 1, 4),
    a::row(K::Record, "column current_h2", 1, 1, 1),
    a::row(K::Record, "column current_h3", 1, 1, 1),
    a::row(K::Record, "column current_h4", 1, 1, 1),
    a::row(K::Record, "column current_h5", 1, 1, 1),
    a::row(K::Record, "column current_h6", 1, 1, 1),
    a::row(K::Record, "column current_h7", 1, 1, 1),
    a::row(K::Record, "column current_mean", 10, 3, 10),
    a::row(K::Record, "column current_range", 16, 3, 16),
    a::row(K::Record, "column cycle", 6, 2, 6),
    a::row(K::Record, "column delta_q", 1, 1, 1),
    a::row(K::Record, "column delta_q_coulomb", 3, 2, 3),
    a::row(K::Record, "column dq", 6, 1, 6),
    a::row(K::Record, "column ece", 2, 2, 2),
    a::row(K::Record, "column ece_amplitude", 2, 1, 2),
    a::row(K::Record, "column ece_mean", 4, 1, 4),
    a::row(K::Record, "column energy_abs", 1, 1, 1),
    a::row(K::Record, "column energy_charge", 3, 1, 3),
    a::row(K::Record, "column energy_discharge", 3, 1, 3),
    a::row(K::Record, "column energy_we", 1, 1, 1),
    a::row(K::Record, "column error", 17, 5, 17),
    a::row(K::Record, "column ewe", 15, 5, 15),
    a::row(K::Record, "column ewe_amplitude", 4, 1, 4),
    a::row(K::Record, "column ewe_h2", 1, 1, 1),
    a::row(K::Record, "column ewe_h3", 1, 1, 1),
    a::row(K::Record, "column ewe_h4", 1, 1, 1),
    a::row(K::Record, "column ewe_h5", 1, 1, 1),
    a::row(K::Record, "column ewe_h6", 1, 1, 1),
    a::row(K::Record, "column ewe_h7", 1, 1, 1),
    a::row(K::Record, "column ewe_mean", 6, 1, 6),
    a::row(K::Record, "column frequency", 5, 1, 5),
    a::row(K::Record, "column half_cycle", 9, 2, 9),
    a::row(K::Record, "column mode", 17, 5, 17),
    a::row(K::Record, "column nsd_current", 1, 1, 1),
    a::row(K::Record, "column nsd_ewe", 1, 1, 1),
    a::row(K::Record, "column nsr_current", 1, 1, 1),
    a::row(K::Record, "column nsr_ewe", 1, 1, 1),
    a::row(K::Record, "column ox_red", 13, 3, 13),
    a::row(K::Record, "column power", 5, 2, 5),
    a::row(K::Record, "column r_compensation", 1, 1, 1),
    a::row(K::Record, "column sequence", 11, 2, 11),
    a::row(K::Record, "column sequence_changes", 9, 2, 9),
    a::row(K::Record, "column step_time", 1, 1, 1),
    a::row(K::Record, "column thd_current", 1, 1, 1),
    a::row(K::Record, "column thd_ewe", 1, 1, 1),
    a::row(K::Record, "column z_cycle", 1, 1, 1),
    a::row(K::Record, "column z_imag_neg", 4, 1, 4),
    a::row(K::Record, "column z_modulus", 5, 1, 5),
    a::row(K::Record, "column z_phase", 5, 1, 5),
    a::row(K::Record, "column z_real", 4, 1, 4),
    a::row(K::Record, "column zce_imag_neg", 2, 1, 2),
    a::row(K::Record, "column zce_modulus", 2, 1, 2),
    a::row(K::Record, "column zce_phase", 2, 1, 2),
    a::row(K::Record, "column zce_real", 2, 1, 2),
    a::row(K::Record, "column zwece_imag_neg", 2, 1, 2),
    a::row(K::Record, "column zwece_modulus", 2, 1, 2),
    a::row(K::Record, "column zwece_phase", 2, 1, 2),
    a::row(K::Record, "column zwece_real", 2, 1, 2),
];
// END GENERATED biologic-mpr

// BEGIN GENERATED biologic-mpt (cargo xtask assurance-audit --write; do not edit)
const BIOLOGIC_MPT_CONFIDENCE: Confidence = Confidence::Medium;
#[rustfmt::skip]
const BIOLOGIC_MPT_VALIDATED: &[Validated] = &[
    a::row(K::Acquisition, "Battery Capacity Determination", 1, 1, 1),
    a::row(K::Acquisition, "Chronoamperometry / Chronocoulometry", 2, 2, 2),
    a::row(K::Acquisition, "Chronopotentiometry", 1, 1, 1),
    a::row(K::Acquisition, "Constant Current", 1, 1, 1),
    a::row(K::Acquisition, "Cyclic Voltammetry", 1, 1, 1),
    a::row(K::Acquisition, "Cyclic Voltammetry Advanced", 1, 1, 1),
    a::row(K::Acquisition, "Galvano Electrochemical Impedance Spectroscopy", 1, 1, 1),
    a::row(K::Acquisition, "Galvanostatic Cycling with Potential Limitation", 1, 1, 1),
    a::row(K::Acquisition, "IR compensation (PEIS)", 1, 1, 1),
    a::row(K::Acquisition, "Linear Sweep Voltammetry", 1, 1, 1),
    a::row(K::Acquisition, "Modulo Bat", 2, 1, 2),
    a::row(K::Acquisition, "Open Circuit Voltage", 1, 1, 1),
    a::row(K::Acquisition, "Potentio Electrochemical Impedance Spectroscopy", 2, 1, 2),
    a::row(K::Dialect, "EC-Lab ASCII FILE", 18, 2, 18),
    a::row(K::Dialect, "decimal comma", 3, 2, 3),
    a::row(K::Dialect, "headerless", 1, 1, 2),
    a::row(K::Field, "experiment.acquisition.started_at", 16, 2, 16),
    a::row(K::Field, "experiment.instrument.model", 16, 2, 16),
    a::row(K::FormatVersion, "EC-Lab ASCII", 18, 2, 18),
    a::row(K::FormatVersion, "EC-Lab ASCII (no header)", 1, 1, 2),
    a::row(K::Record, "column analog_in_1", 1, 1, 1),
    a::row(K::Record, "column analog_in_2", 1, 1, 1),
    a::row(K::Record, "column c", 4, 1, 4),
    a::row(K::Record, "column capacitance_charge", 8, 2, 8),
    a::row(K::Record, "column capacitance_discharge", 8, 2, 8),
    a::row(K::Record, "column capacitance_parallel", 3, 1, 4),
    a::row(K::Record, "column capacitance_series", 3, 1, 4),
    a::row(K::Record, "column capacity", 9, 2, 9),
    a::row(K::Record, "column charge", 9, 1, 10),
    a::row(K::Record, "column charge_coulomb", 6, 2, 6),
    a::row(K::Record, "column charge_half_cycle", 9, 2, 9),
    a::row(K::Record, "column conductivity_ms", 4, 1, 4),
    a::row(K::Record, "column control", 4, 1, 4),
    a::row(K::Record, "column control_changes", 12, 2, 12),
    a::row(K::Record, "column control_current", 7, 1, 7),
    a::row(K::Record, "column control_potential", 9, 2, 9),
    a::row(K::Record, "column counter_increment", 10, 2, 10),
    a::row(K::Record, "column current", 5, 1, 5),
    a::row(K::Record, "column current_amplitude", 4, 1, 5),
    a::row(K::Record, "column current_h2", 1, 1, 1),
    a::row(K::Record, "column current_h3", 1, 1, 1),
    a::row(K::Record, "column current_h4", 1, 1, 1),
    a::row(K::Record, "column current_h5", 1, 1, 1),
    a::row(K::Record, "column current_h6", 1, 1, 1),
    a::row(K::Record, "column current_h7", 1, 1, 1),
    a::row(K::Record, "column current_mean", 11, 2, 12),
    a::row(K::Record, "column current_range", 15, 2, 16),
    a::row(K::Record, "column cycle", 14, 2, 15),
    a::row(K::Record, "column delta_q", 1, 1, 1),
    a::row(K::Record, "column delta_q_coulomb", 3, 2, 3),
    a::row(K::Record, "column dq", 9, 1, 10),
    a::row(K::Record, "column ece", 2, 2, 2),
    a::row(K::Record, "column ece_amplitude", 2, 1, 2),
    a::row(K::Record, "column ece_mean", 4, 1, 4),
    a::row(K::Record, "column efficiency", 9, 2, 9),
    a::row(K::Record, "column energy_abs", 1, 1, 1),
    a::row(K::Record, "column energy_charge", 7, 2, 7),
    a::row(K::Record, "column energy_discharge", 7, 2, 7),
    a::row(K::Record, "column energy_we", 1, 1, 1),
    a::row(K::Record, "column energy_we_charge", 1, 1, 1),
    a::row(K::Record, "column energy_we_discharge", 1, 1, 1),
    a::row(K::Record, "column error", 14, 2, 14),
    a::row(K::Record, "column ewe", 13, 3, 13),
    a::row(K::Record, "column ewe_amplitude", 4, 1, 5),
    a::row(K::Record, "column ewe_ece", 5, 2, 5),
    a::row(K::Record, "column ewe_h2", 1, 1, 1),
    a::row(K::Record, "column ewe_h3", 1, 1, 1),
    a::row(K::Record, "column ewe_h4", 1, 1, 1),
    a::row(K::Record, "column ewe_h5", 1, 1, 1),
    a::row(K::Record, "column ewe_h6", 1, 1, 1),
    a::row(K::Record, "column ewe_h7", 1, 1, 1),
    a::row(K::Record, "column ewe_mean", 6, 1, 7),
    a::row(K::Record, "column frequency", 5, 1, 6),
    a::row(K::Record, "column half_cycle", 9, 2, 9),
    a::row(K::Record, "column im_c", 4, 1, 4),
    a::row(K::Record, "column im_conductivity_ms", 4, 1, 4),
    a::row(K::Record, "column im_m", 4, 1, 4),
    a::row(K::Record, "column im_permittivity", 4, 1, 4),
    a::row(K::Record, "column im_resistivity", 4, 1, 4),
    a::row(K::Record, "column im_y", 5, 1, 6),
    a::row(K::Record, "column loss_angle_delta", 4, 1, 4),
    a::row(K::Record, "column m", 4, 1, 4),
    a::row(K::Record, "column mode", 14, 2, 14),
    a::row(K::Record, "column nsd_current", 1, 1, 1),
    a::row(K::Record, "column nsd_ewe", 1, 1, 1),
    a::row(K::Record, "column nsr_current", 1, 1, 1),
    a::row(K::Record, "column nsr_ewe", 1, 1, 1),
    a::row(K::Record, "column ox_red", 12, 2, 12),
    a::row(K::Record, "column pce", 1, 1, 1),
    a::row(K::Record, "column permittivity", 4, 1, 4),
    a::row(K::Record, "column phase_c", 4, 1, 4),
    a::row(K::Record, "column phase_conductivity", 4, 1, 4),
    a::row(K::Record, "column phase_m", 4, 1, 4),
    a::row(K::Record, "column phase_permittivity", 4, 1, 4),
    a::row(K::Record, "column phase_resistivity", 4, 1, 4),
    a::row(K::Record, "column phase_y", 5, 1, 6),
    a::row(K::Record, "column power", 14, 2, 14),
    a::row(K::Record, "column pwe_ce", 1, 1, 1),
    a::row(K::Record, "column q_charge", 9, 2, 9),
    a::row(K::Record, "column q_discharge", 9, 2, 9),
    a::row(K::Record, "column r", 1, 1, 1),
    a::row(K::Record, "column r_compensation", 1, 1, 1),
    a::row(K::Record, "column rce", 1, 1, 1),
    a::row(K::Record, "column re_c", 4, 1, 4),
    a::row(K::Record, "column re_conductivity_ms", 4, 1, 4),
    a::row(K::Record, "column re_m", 4, 1, 4),
    a::row(K::Record, "column re_permittivity", 4, 1, 4),
    a::row(K::Record, "column re_resistivity", 4, 1, 4),
    a::row(K::Record, "column re_y", 5, 1, 6),
    a::row(K::Record, "column resistivity", 4, 1, 4),
    a::row(K::Record, "column rwe", 5, 1, 5),
    a::row(K::Record, "column rwe_ce", 1, 1, 1),
    a::row(K::Record, "column sequence", 11, 2, 11),
    a::row(K::Record, "column sequence_changes", 9, 2, 9),
    a::row(K::Record, "column step_time", 6, 2, 6),
    a::row(K::Record, "column tan_delta", 4, 1, 4),
    a::row(K::Record, "column thd_current", 1, 1, 1),
    a::row(K::Record, "column thd_ewe", 1, 1, 1),
    a::row(K::Record, "column x", 5, 1, 5),
    a::row(K::Record, "column y", 5, 1, 6),
    a::row(K::Record, "column z_cycle", 1, 1, 1),
    a::row(K::Record, "column z_imag_neg", 5, 1, 6),
    a::row(K::Record, "column z_modulus", 5, 1, 6),
    a::row(K::Record, "column z_phase", 5, 1, 6),
    a::row(K::Record, "column z_real", 5, 1, 6),
    a::row(K::Record, "column zce_imag_neg", 2, 1, 2),
    a::row(K::Record, "column zce_modulus", 2, 1, 2),
    a::row(K::Record, "column zce_phase", 2, 1, 2),
    a::row(K::Record, "column zce_real", 2, 1, 2),
    a::row(K::Record, "column zwece_imag_neg", 2, 1, 2),
    a::row(K::Record, "column zwece_modulus", 2, 1, 2),
    a::row(K::Record, "column zwece_phase", 2, 1, 2),
    a::row(K::Record, "column zwece_real", 2, 1, 2),
];
// END GENERATED biologic-mpt

// BEGIN GENERATED gamry-dta (cargo xtask assurance-audit --write; do not edit)
const GAMRY_DTA_CONFIDENCE: Confidence = Confidence::Medium;
#[rustfmt::skip]
const GAMRY_DTA_VALIDATED: &[Validated] = &[
    a::row(K::Acquisition, "experiment CV", 2, 2, 2),
    a::row(K::Acquisition, "experiment EISPOT", 2, 2, 3),
    a::row(K::Acquisition, "experiment LSV", 1, 1, 1),
    a::row(K::Field, "experiment.acquisition.started_at", 5, 3, 6),
    a::row(K::FormatVersion, "EXPLAIN CV", 2, 2, 2),
    a::row(K::FormatVersion, "EXPLAIN EISPOT", 2, 2, 3),
    a::row(K::FormatVersion, "EXPLAIN LSV", 1, 1, 1),
    a::row(K::Record, "column aux_channel", 5, 3, 6),
    a::row(K::Record, "column current", 3, 2, 3),
    a::row(K::Record, "column current_dc", 2, 2, 3),
    a::row(K::Record, "column current_range", 5, 3, 6),
    a::row(K::Record, "column cycle", 1, 1, 1),
    a::row(K::Record, "column frequency", 2, 2, 3),
    a::row(K::Record, "column i", 0, 0, 1),
    a::row(K::Record, "column point", 5, 3, 6),
    a::row(K::Record, "column potential", 5, 3, 6),
    a::row(K::Record, "column potential_dc", 2, 2, 3),
    a::row(K::Record, "column potential_measured", 3, 2, 4),
    a::row(K::Record, "column potential_uncompensated", 3, 2, 3),
    a::row(K::Record, "column signal", 3, 2, 3),
    a::row(K::Record, "column temperature", 4, 2, 5),
    a::row(K::Record, "column v", 0, 0, 1),
    a::row(K::Record, "column z_imag", 2, 2, 3),
    a::row(K::Record, "column z_modulus", 2, 2, 3),
    a::row(K::Record, "column z_phase", 2, 2, 3),
    a::row(K::Record, "column z_real", 2, 2, 3),
    a::row(K::Record, "column z_signal", 2, 2, 3),
    a::row(K::Record, "table CURVE", 3, 2, 3),
    a::row(K::Record, "table FRACURVE", 0, 0, 1),
    a::row(K::Record, "table OCVCURVE", 3, 2, 4),
    a::row(K::Record, "table ZCURVE", 2, 2, 3),
];
// END GENERATED gamry-dta

// BEGIN GENERATED neware-nda (cargo xtask assurance-audit --write; do not edit)
const NEWARE_NDA_CONFIDENCE: Confidence = Confidence::Medium;
#[rustfmt::skip]
const NEWARE_NDA_VALIDATED: &[Validated] = &[
    a::row(K::Field, "experiment.acquisition.started_at", 5, 2, 5),
    a::row(K::FormatVersion, "nda 130", 3, 2, 3),
    a::row(K::FormatVersion, "nda 29", 2, 1, 2),
    a::row(K::Layout, "BTS 9.0 records of 88 bytes", 1, 1, 1),
    a::row(K::Layout, "BTS 9.1 records of 52 bytes", 1, 1, 1),
    a::row(K::Layout, "BTS 9.1 records of 56 bytes", 1, 1, 1),
    a::row(K::Layout, "records of 86 bytes", 2, 1, 2),
    a::row(K::Record, "column charge_capacity", 5, 2, 5),
    a::row(K::Record, "column charge_energy", 5, 2, 5),
    a::row(K::Record, "column current", 5, 2, 5),
    a::row(K::Record, "column cycle", 4, 2, 4),
    a::row(K::Record, "column discharge_capacity", 5, 2, 5),
    a::row(K::Record, "column discharge_energy", 5, 2, 5),
    a::row(K::Record, "column record", 5, 2, 5),
    a::row(K::Record, "column step_index", 5, 2, 5),
    a::row(K::Record, "column step_time", 3, 1, 3),
    a::row(K::Record, "column step_type", 5, 2, 5),
    a::row(K::Record, "column temperature", 1, 1, 1),
    a::row(K::Record, "column voltage", 5, 2, 5),
];
// END GENERATED neware-nda

// BEGIN GENERATED neware-ndax (cargo xtask assurance-audit --write; do not edit)
const NEWARE_NDAX_CONFIDENCE: Confidence = Confidence::Medium;
#[rustfmt::skip]
const NEWARE_NDAX_VALIDATED: &[Validated] = &[
    a::row(K::Field, "experiment.acquisition.started_at", 4, 3, 4),
    a::row(K::FormatVersion, "ndc 14", 2, 1, 2),
    a::row(K::FormatVersion, "ndc 17", 1, 1, 1),
    a::row(K::FormatVersion, "ndc 5", 1, 1, 1),
    a::row(K::Layout, "voltage and current records with separate step and run files", 3, 2, 3),
    a::row(K::Layout, "whole records of 87 bytes", 1, 1, 1),
    a::row(K::Record, "column aux", 1, 1, 1),
    a::row(K::Record, "column aux_1122_1", 1, 1, 1),
    a::row(K::Record, "column aux_temperature", 2, 2, 2),
    a::row(K::Record, "column aux_temperature_1", 2, 2, 2),
    a::row(K::Record, "column aux_temperature_2", 1, 1, 1),
    a::row(K::Record, "column aux_voltage", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_1", 1, 1, 1),
    a::row(K::Record, "column charge_capacity", 4, 3, 4),
    a::row(K::Record, "column charge_energy", 4, 3, 4),
    a::row(K::Record, "column current", 4, 3, 4),
    a::row(K::Record, "column cycle", 4, 3, 4),
    a::row(K::Record, "column discharge_capacity", 4, 3, 4),
    a::row(K::Record, "column discharge_energy", 4, 3, 4),
    a::row(K::Record, "column record", 4, 3, 4),
    a::row(K::Record, "column step_index", 4, 3, 4),
    a::row(K::Record, "column step_time", 4, 3, 4),
    a::row(K::Record, "column step_type", 4, 3, 4),
    a::row(K::Record, "column voltage", 4, 3, 4),
];
// END GENERATED neware-ndax

// BEGIN GENERATED arbin-res (cargo xtask assurance-audit --write; do not edit)
const ARBIN_RES_CONFIDENCE: Confidence = Confidence::Medium;
#[rustfmt::skip]
const ARBIN_RES_VALIDATED: &[Validated] = &[
    a::row(K::Field, "experiment.acquisition.started_at", 0, 0, 7),
    a::row(K::FormatVersion, "Results File 20171213", 1, 1, 1),
    a::row(K::FormatVersion, "Results File 4.145", 1, 1, 1),
    a::row(K::FormatVersion, "Results File 5.23", 3, 3, 3),
    a::row(K::FormatVersion, "Results File 5.26", 2, 1, 2),
    a::row(K::Layout, "Jet 4 database", 7, 4, 7),
    a::row(K::Record, "column ac_impedance", 7, 4, 7),
    a::row(K::Record, "column aci_phase_angle", 7, 4, 7),
    a::row(K::Record, "column acr", 1, 1, 1),
    a::row(K::Record, "column aux_temperature", 3, 2, 3),
    a::row(K::Record, "column aux_temperature_1", 3, 2, 3),
    a::row(K::Record, "column aux_temperature_1_rate", 1, 1, 1),
    a::row(K::Record, "column aux_temperature_2", 1, 1, 1),
    a::row(K::Record, "column aux_temperature_3", 1, 1, 1),
    a::row(K::Record, "column aux_temperature_4", 1, 1, 1),
    a::row(K::Record, "column aux_temperature_5", 1, 1, 1),
    a::row(K::Record, "column aux_temperature_6", 1, 1, 1),
    a::row(K::Record, "column aux_temperature_7", 1, 1, 1),
    a::row(K::Record, "column aux_temperature_8", 1, 1, 1),
    a::row(K::Record, "column aux_voltage", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_1", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_10", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_11", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_12", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_2", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_3", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_4", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_5", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_6", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_7", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_8", 1, 1, 1),
    a::row(K::Record, "column aux_voltage_9", 1, 1, 1),
    a::row(K::Record, "column charge_capacity", 7, 4, 7),
    a::row(K::Record, "column charge_energy", 7, 4, 7),
    a::row(K::Record, "column current", 7, 4, 7),
    a::row(K::Record, "column cycle", 7, 4, 7),
    a::row(K::Record, "column date_time", 7, 4, 7),
    a::row(K::Record, "column discharge_capacity", 7, 4, 7),
    a::row(K::Record, "column discharge_energy", 7, 4, 7),
    a::row(K::Record, "column dv_dt", 7, 4, 7),
    a::row(K::Record, "column fc_data", 7, 4, 7),
    a::row(K::Record, "column internal_resistance", 7, 4, 7),
    a::row(K::Record, "column pulse_stage_index", 1, 1, 1),
    a::row(K::Record, "column pulse_stage_time", 1, 1, 1),
    a::row(K::Record, "column record", 7, 4, 7),
    a::row(K::Record, "column step_index", 7, 4, 7),
    a::row(K::Record, "column step_time", 7, 4, 7),
    a::row(K::Record, "column tc_counter1", 1, 1, 1),
    a::row(K::Record, "column tc_counter2", 1, 1, 1),
    a::row(K::Record, "column tc_counter3", 1, 1, 1),
    a::row(K::Record, "column tc_counter4", 1, 1, 1),
    a::row(K::Record, "column voltage", 7, 4, 7),
    a::row(K::Record, "table events", 7, 4, 7),
    a::row(K::Record, "table statistics", 5, 4, 5),
    a::row(K::WriterVersion, "MITS Pro 4.32", 2, 1, 2),
    a::row(K::WriterVersion, "MITS Pro 7.00", 1, 1, 1),
];
// END GENERATED arbin-res
