//! `cargo xtask health [--write] [--reports DIR]`: an internal project-health report generated
//! from the repository: formats and their confidence distribution, corpus size and depositors,
//! the assurance evidence, held-out results, open findings (new-variant intakes, disagreements,
//! adjudications, oracle skips) and the maintenance safety nets (guides, snapshots, fuzz
//! targets). Without `--write` the task prints the report. `--write` saves it to
//! `target/reports/health.md`, which is not committed.
//!
//! Benchmark reports are kept outside the repository. `--reports DIR` (or the
//! `OPENREADOUT_REPORTS` environment variable) names the folder that holds them: the latest
//! `heldout-*.json` run and `second-opinions.md`. Without it the report leaves those parts out.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::Result;

use crate::repo;

const PAGE: &str = "target/reports/health.md";

pub fn run(write: bool, reports: Option<PathBuf>) -> Result<()> {
    let root = crate::root();
    let reports = reports.or_else(|| std::env::var_os("OPENREADOUT_REPORTS").map(PathBuf::from));
    let page = render(&root, reports.as_deref())?;
    if write {
        let path = root.join(PAGE);
        if let Some(dir) = path.parent() {
            fs::create_dir_all(dir)?;
        }
        fs::write(&path, &page)?;
        println!("wrote {PAGE}");
    } else {
        print!("{page}");
    }
    Ok(())
}

fn count_files(dir: &Path, ext: &str) -> usize {
    let mut n = 0;
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        let Ok(rd) = fs::read_dir(&d) else { continue };
        for e in rd.filter_map(std::result::Result::ok) {
            let p = e.path();
            if p.is_dir() {
                if !p.ends_with("target") {
                    stack.push(p);
                }
            } else if p.extension().is_some_and(|x| x == ext)
                // committed ground truth over 1 MiB is `<name>.json.gz` (`cargo xtask corpus compress`)
                || p.to_str().is_some_and(|s| s.ends_with(&format!(".{ext}.gz")))
            {
                n += 1;
            }
        }
    }
    n
}

fn human(b: u64) -> String {
    const U: [&str; 5] = ["B", "kB", "MB", "GB", "TB"];
    #[allow(clippy::cast_precision_loss)]
    let mut v = b as f64;
    let mut i = 0;
    while v >= 1000.0 && i < U.len() - 1 {
        v /= 1000.0;
        i += 1;
    }
    format!("{v:.1} {}", U[i])
}

fn pct(a: usize, b: usize) -> String {
    if b == 0 {
        "-".into()
    } else {
        #[allow(clippy::cast_precision_loss)]
        let p = 100.0 * a as f64 / b as f64;
        format!("{p:.0}%")
    }
}

fn render(root: &Path, reports: Option<&Path>) -> Result<String> {
    let crates = repo::reader_crates(root)?;
    let manifest = repo::manifest(root)?;
    let ev = repo::evidence(root)?;
    let mut s = String::from(
        "# Project health\n\n<!-- generated by `cargo xtask health` from the repository; internal, not published -->\n\nThe state of the project, computed from the files in the repository: the readers and how well each is validated, the test corpus, the held-out benchmark, open findings, and the safety nets that let a new maintainer change a reader without breaking another. docs/maintaining.md explains how each number is used.\n\n",
    );

    readers(&mut s, &crates)?;
    corpus(&mut s, &crates, &manifest, &ev);
    evidence(&mut s, &ev, &crate::assurance::feature_validation(root)?);
    heldout(&mut s, reports, &ev)?;
    findings(&mut s, root, reports, &manifest)?;
    safety_nets(&mut s, root, &crates);
    Ok(s)
}

/// Formats per confidence level and the knowledge basis of their readers.
fn readers(s: &mut String, crates: &[repo::ReaderCrate]) -> Result<()> {
    let mut by_level: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut basis: BTreeMap<String, usize> = BTreeMap::new();
    for c in crates {
        let profile = fs::read_to_string(c.dir.join("src/assurance.rs"))?;
        for f in &c.formats {
            let ident = f.to_ascii_uppercase().replace('-', "_");
            let needle = format!("const {ident}_CONFIDENCE: Confidence = Confidence::");
            let level = profile.find(&needle).map_or_else(
                || "unknown".to_string(),
                |i| {
                    profile[i + needle.len()..]
                        .chars()
                        .take_while(char::is_ascii_alphabetic)
                        .collect::<String>()
                        .to_ascii_lowercase()
                },
            );
            by_level.entry(level).or_default().push(format!("`{f}`"));
            let b = profile
                .find(&format!("format_id: \"{f}\""))
                .and_then(|i| {
                    let rest = &profile[i..];
                    rest.find("basis: Basis::").map(|j| {
                        rest[j + 14..]
                            .chars()
                            .take_while(char::is_ascii_alphanumeric)
                            .collect::<String>()
                    })
                })
                .unwrap_or_else(|| "unknown".into());
            *basis.entry(b).or_default() += 1;
        }
    }
    let nformats: usize = by_level.values().map(Vec::len).sum();
    let _ = writeln!(
        s,
        "## Readers\n\n{nformats} formats in {} reader crates. Confidence is computed from the corpus evidence by the confidence rubric in docs/assurance.md, not set by hand; per-format detail is in evidence.md (`cargo xtask assurance-audit --write`).\n\n| confidence | formats | which |\n| --- | --- | --- |",
        crates.len()
    );
    for level in ["high", "medium", "low", "unknown"] {
        if let Some(v) = by_level.get(level) {
            let _ = writeln!(s, "| {level} | {} | {} |", v.len(), v.join(", "));
        }
    }
    let _ = writeln!(
        s,
        "\nKnowledge basis: {}.\n",
        basis
            .iter()
            .map(|(b, n)| format!(
                "{n} {}",
                b.chars().fold(String::new(), |mut acc, c| {
                    if c.is_ascii_uppercase() && !acc.is_empty() {
                        acc.push(' ');
                    }
                    acc.push(c.to_ascii_lowercase());
                    acc
                })
            ))
            .collect::<Vec<_>>()
            .join(", ")
    );
    Ok(())
}

/// Manifest entries per tier, development inputs and depositors.
fn corpus(
    s: &mut String,
    crates: &[repo::ReaderCrate],
    manifest: &[repo::Entry],
    ev: &repo::Evidence,
) {
    let mut tiers: BTreeMap<String, (usize, u64)> = BTreeMap::new();
    for e in manifest {
        let t = tiers.entry(e.tier.clone()).or_default();
        t.0 += 1;
        t.1 += e.size;
    }
    let dev: Vec<&repo::Entry> = manifest
        .iter()
        .filter(|e| repo::is_development_input(e))
        .collect();
    // depositors (source records) as the assurance evidence counts them
    let dev_sources: BTreeSet<&str> = ev
        .files
        .iter()
        .filter(|f| !f.synthetic)
        .map(|f| f.source.as_str())
        .collect();
    let dev_formats: BTreeSet<&str> = dev.iter().map(|e| e.format.as_str()).collect();
    let heldout_inputs = manifest
        .iter()
        .filter(|e| e.role == crate::heldout::ROLE)
        .count();
    let no_url = dev.iter().filter(|e| e.url.is_empty()).count();
    let licences: BTreeSet<&str> = manifest
        .iter()
        .map(|e| e.license.split([' ', '(', ';']).next().unwrap_or(""))
        .filter(|l| !l.is_empty())
        .collect();
    let _ = writeln!(
        s,
        "## Corpus\n\n{} manifest entries; {} development inputs of {} formats from {} depositors (distinct source records: a Zenodo record, a study, a repository) ({no_url} without a download URL: synthetic fixtures and bundle members); {heldout_inputs} held-out inputs. Licences recorded: {} distinct (every entry has one).\n\n| tier | entries | declared size |\n| --- | --- | --- |",
        manifest.len(),
        dev.len(),
        dev_formats.len(),
        dev_sources.len(),
        licences.len()
    );
    for (t, (n, b)) in &tiers {
        let _ = writeln!(
            s,
            "| {} | {n} | {} |",
            if t.is_empty() { "(none)" } else { t },
            human(*b)
        );
    }
    let missing: Vec<String> = crates
        .iter()
        .flat_map(|c| c.formats.iter())
        .filter(|f| !dev_formats.contains(f.as_str()))
        .map(|f| format!("`{f}`"))
        .collect();
    if !missing.is_empty() {
        let _ = writeln!(
            s,
            "\nFormats without a development-corpus input of their own id (read through a sibling format's files, or not yet in the corpus): {}.",
            missing.join(", ")
        );
    }
}

/// Oracle agreement and validated variant-feature values from the assurance evidence.
fn evidence(
    s: &mut String,
    ev: &repo::Evidence,
    values: &BTreeMap<(String, String, String), bool>,
) {
    let read = ev.files.iter().filter(|f| f.oracle != "unreadable").count();
    let with_oracle = ev
        .files
        .iter()
        .filter(|f| matches!(f.oracle.as_str(), "pass" | "FAIL"))
        .count();
    let passes = ev.files.iter().filter(|f| f.oracle == "pass").count();
    let confirmed = ev
        .files
        .iter()
        .filter(|f| f.oracle == "pass" && f.independent)
        .count();
    let fails: Vec<String> = ev
        .files
        .iter()
        .filter(|f| f.oracle == "FAIL")
        .map(|f| format!("`{}` ({})", f.id, f.format))
        .collect();
    let unreadable: Vec<String> = ev
        .files
        .iter()
        .filter(|f| f.oracle == "unreadable")
        .map(|f| format!("`{}` ({})", f.id, f.format))
        .collect();
    // validated exactly as the assurance audit validates them (tracked fields, vendor-stored
    // results and scopes included), so this page and the generated tables agree
    let validated_values = values.values().filter(|v| **v).count();
    let _ = writeln!(
        s,
        "\n## Assurance evidence\n\nFrom `corpus/assurance/evidence.json` (development files only): {read} files read; {with_oracle} compared with an oracle, {passes} agree ({}); {confirmed} confirmed by an independent reader. {} distinct variant-feature values observed, {validated_values} of them validated ({}); the others make files that use them `partially_validated` or `unvalidated`.\n",
        pct(passes, with_oracle),
        values.len(),
        pct(validated_values, values.len())
    );
    if !fails.is_empty() {
        let _ = writeln!(
            s,
            "Development files that disagree with their oracle ({}): {}.\n",
            fails.len(),
            fails.join(", ")
        );
    }
    if !unreadable.is_empty() {
        let _ = writeln!(
            s,
            "Development files `info` cannot read ({}): {}.\n",
            unreadable.len(),
            unreadable.join(", ")
        );
    }
    // decode paths the corpus reaches but no independent reader confirms: files using them are
    // `partially_validated` (descriptive features) or `unvalidated` for the outputs they affect
    let mut unconfirmed_values: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    for ((format, kind, value), ok) in values {
        if !ok {
            unconfirmed_values
                .entry(format.as_str())
                .or_default()
                .push(format!("{kind}=`{}`", value.replace('|', "\\|")));
        }
    }
    if !unconfirmed_values.is_empty() {
        s.push_str("Variant values the development corpus reaches but no independent reader confirms (each a decode path to confirm with a new file and an oracle):\n\n| format | values |\n| --- | --- |\n");
        for (f, v) in &unconfirmed_values {
            let _ = writeln!(s, "| `{f}` | {} |", v.join(", "));
        }
        s.push('\n');
    }
}

/// The latest held-out benchmark report (when `reports_dir` names the folder that holds the
/// reports) and the held-out results in the evidence.
fn heldout(s: &mut String, reports_dir: Option<&Path>, ev: &repo::Evidence) -> Result<()> {
    let mut reports: Vec<String> = reports_dir
        .and_then(|d| fs::read_dir(d).ok())
        .into_iter()
        .flatten()
        .filter_map(std::result::Result::ok)
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| {
            n.starts_with("heldout-")
                && Path::new(n)
                    .extension()
                    .is_some_and(|e| e.eq_ignore_ascii_case("json"))
                && !n.contains("classes")
        })
        .collect();
    reports.sort();
    s.push_str("## Held-out benchmark\n\n");
    if let (Some(dir), Some(latest)) = (reports_dir, reports.last()) {
        let v: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(dir.join(latest))?).unwrap_or_default();
        let files = v["files"].as_array().cloned().unwrap_or_default();
        let mut status: BTreeMap<String, usize> = BTreeMap::new();
        let mut levels: BTreeMap<String, usize> = BTreeMap::new();
        for f in &files {
            *status
                .entry(f["status"].as_str().unwrap_or("?").to_string())
                .or_default() += 1;
            *levels
                .entry(
                    f["assurance"]["level"]
                        .as_str()
                        .unwrap_or("refused")
                        .to_string(),
                )
                .or_default() += 1;
        }
        let md = latest.trim_end_matches(".json").to_string() + ".md";
        let _ = writeln!(
            s,
            "Latest run: {md} ({} held-out inputs never used for development; rules in docs/benchmark/heldout.md).\n\n| outcome | files |\n| --- | --- |",
            files.len()
        );
        for (k, n) in &status {
            let _ = writeln!(s, "| {k} | {n} |");
        }
        let _ = writeln!(
            s,
            "\nAssurance of those files: {}.",
            levels
                .iter()
                .map(|(k, n)| format!("{n} {}", k.replace('_', " ")))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    let (hp, hf) = ev
        .heldout
        .values()
        .fold((0, 0), |(p, f), h| (p + h.pass, f + h.fail));
    let _ = writeln!(
        s,
        "\nHeld-out corpus-test results in the evidence (what the confidence rubric uses): {hp} pass, {hf} fail.\n"
    );
    Ok(())
}

/// Intakes, adjudications, oracle skips, unconfirmed licences and upstream bugs.
fn findings(
    s: &mut String,
    root: &Path,
    reports: Option<&Path>,
    manifest: &[repo::Entry],
) -> Result<()> {
    s.push_str("## Open findings\n\n");
    let mut intakes: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let dir = root.join("corpus/intake");
    if dir.is_dir() {
        for e in fs::read_dir(&dir)?.filter_map(std::result::Result::ok) {
            let p = e.path();
            if p.extension().is_some_and(|x| x == "toml") {
                let r: crate::variant::Record = toml::from_str(&fs::read_to_string(&p)?)?;
                intakes
                    .entry(r.status.clone())
                    .or_default()
                    .push(format!("`{}` ({})", r.id, r.format));
            }
        }
    }
    let _ = writeln!(
        s,
        "- New-variant intakes (`corpus/intake/`): {}.",
        if intakes.is_empty() {
            "none".to_string()
        } else {
            intakes
                .iter()
                .map(|(k, v)| format!("{} {k}: {}", v.len(), v.join(", ")))
                .collect::<Vec<_>>()
                .join("; ")
        }
    );
    let adj = fs::read_to_string(root.join("corpus/oracle/second/adjudications.toml"))
        .unwrap_or_default();
    // Whole-file entries (`[file.*]`, `[recorded.*]`: second_opinion.rs) and field entries
    // (`[[field]]`: second_fields.rs, one entry covering several files and fields). The number of
    // field differences they settle is counted by the test run, in second-opinions.md (written by
    // oracle/second_report.py and kept with the other reports).
    let adjudicated = adj
        .lines()
        .filter(|l| l.starts_with("[file.") || l.starts_with("[recorded."))
        .count();
    let field_entries = adj.lines().filter(|l| l.trim() == "[[field]]").count();
    let neither = adj
        .lines()
        .filter(|l| l.trim() == "right = \"neither\"")
        .count();
    let field_differences = reports
        .and_then(|d| fs::read_to_string(d.join("second-opinions.md")).ok())
        .and_then(|t| {
            let line = t.lines().find(|l| l.starts_with("All families:"))?;
            let (before, _) = line.split_once(" adjudicated differences")?;
            before.rsplit(' ').next()?.parse::<u64>().ok()
        });
    let _ = writeln!(
        s,
        "- Second-opinion disagreements adjudicated (`corpus/oracle/second/adjudications.toml`, {neither} where neither reader was right): {adjudicated} whole-file entries, and {field_entries} field entries{}.",
        field_differences.map_or_else(String::new, |n| format!(
            " that settle {n} per-file field differences (second-opinions.md)"
        ))
    );
    let skips = fs::read_to_string(root.join("corpus/manifest.toml"))
        .unwrap_or_default()
        .lines()
        .filter(|l| l.trim_start().starts_with("oracle_skip"))
        .count();
    let _ = writeln!(
        s,
        "- Corpus files whose oracle is known to disagree for a documented reason (`oracle_skip`): {skips}."
    );
    let unconfirmed = manifest
        .iter()
        .filter(|e| e.license.contains("UNCONFIRMED") || e.source.contains("UNCONFIRMED"))
        .count();
    let _ = writeln!(
        s,
        "- Corpus entries whose licence or source is not yet confirmed (from intakes; tier `hold`, not fetched automatically): {unconfirmed}."
    );
    let upstream = root.join("fuzz/known-upstream");
    let upstream_n = fs::read_dir(&upstream).map_or(0, Iterator::count);
    let _ = writeln!(
        s,
        "- Known upstream dependency bugs with reproducers (`fuzz/known-upstream/`): {upstream_n}.\n"
    );
    Ok(())
}

/// Maintainer guides, snapshots, ground truth and fuzz targets.
fn safety_nets(s: &mut String, root: &Path, crates: &[repo::ReaderCrate]) {
    let guides = crates
        .iter()
        .filter(|c| c.dir.join("MAINTAINING.md").exists())
        .count();
    let fixture_snaps =
        fs::read_to_string(root.join("crates/openreadout-cli/tests/snapshots/fixtures.jsonl"))
            .map_or(0, |t| t.lines().count());
    let corpus_snaps: usize = fs::read_dir(root.join("corpus/snapshots")).map_or(0, |rd| {
        rd.filter_map(std::result::Result::ok)
            .map(|e| fs::read_to_string(e.path()).map_or(0, |t| t.lines().count()))
            .sum()
    });
    let fuzz_targets = count_files(&root.join("fuzz/fuzz_targets"), "rs");
    let oracles = count_files(&root.join("corpus/oracle"), "json");
    let rust_files = count_files(&root.join("crates"), "rs");
    let _ = writeln!(
        s,
        "## Safety nets for maintainers\n\n| what | count |\n| --- | --- |\n| reader crates with a maintainer guide (`MAINTAINING.md`, generated facts checked by `cargo xtask guides`) | {guides} of {} |\n| golden-output snapshots of committed fixtures (`cargo test`) | {fixture_snaps} |\n| golden-output snapshots of development-corpus files | {corpus_snaps} |\n| committed ground-truth files (`corpus/oracle/**.json`, `.json.gz` over 1 MiB) | {oracles} |\n| fuzz targets (`fuzz/fuzz_targets/`) | {fuzz_targets} |\n| Rust source files under `crates/` | {rust_files} |",
        crates.len()
    );
}
