//! `cargo xtask r-vendor`: make the R package (`r/openreadout`) self-contained for
//! `R CMD build` / CRAN.
//!
//! Inside a checkout the package builds `crates/openreadout-r` from the workspace. A source
//! tarball cannot reach the workspace, so this copies the crates it needs into
//! `r/openreadout/src/rust/` (a small workspace of its own: the root manifest's package fields,
//! workspace dependencies, lints and profiles), vendors every crates.io dependency with
//! `cargo vendor` into `src/rust/vendor.tar.xz`, and writes the source replacement
//! `src/rust/vendor-config.toml`. `configure` then builds offline from those files. Dev-only
//! sections (dev-dependencies, tests, benches, examples) are left out, and the vendored crates'
//! test, bench and example directories are dropped to keep the tarball small.

use std::collections::{BTreeSet, VecDeque};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

const ROOT_CRATE: &str = "openreadout-r";

/// Workspace crates (directory names under `crates/`) the R crate needs, itself included.
fn needed_crates(root: &Path) -> Result<BTreeSet<String>> {
    let mut seen = BTreeSet::new();
    let mut queue = VecDeque::from([ROOT_CRATE.to_string()]);
    while let Some(name) = queue.pop_front() {
        if !seen.insert(name.clone()) {
            continue;
        }
        let manifest = root.join("crates").join(&name).join("Cargo.toml");
        let text = fs::read_to_string(&manifest)
            .with_context(|| format!("reading {}", manifest.display()))?;
        let doc: toml::Table = text.parse()?;
        let mut tables: Vec<&toml::Table> = Vec::new();
        for key in ["dependencies", "build-dependencies"] {
            if let Some(t) = doc.get(key).and_then(toml::Value::as_table) {
                tables.push(t);
            }
        }
        if let Some(targets) = doc.get("target").and_then(toml::Value::as_table) {
            for t in targets.values().filter_map(toml::Value::as_table) {
                for key in ["dependencies", "build-dependencies"] {
                    if let Some(d) = t.get(key).and_then(toml::Value::as_table) {
                        tables.push(d);
                    }
                }
            }
        }
        for t in tables {
            for dep in t.keys() {
                if dep.starts_with("openreadout-") && root.join("crates").join(dep).is_dir() {
                    queue.push_back(dep.clone());
                }
            }
        }
    }
    Ok(seen)
}

/// The root manifest reduced to a workspace of `crates`.
fn root_manifest(root: &Path, crates: &BTreeSet<String>) -> Result<String> {
    let mut doc: toml::Table = fs::read_to_string(root.join("Cargo.toml"))?.parse()?;
    let ws = doc
        .get_mut("workspace")
        .and_then(toml::Value::as_table_mut)
        .context("root Cargo.toml has no [workspace]")?;
    ws.insert(
        "members".into(),
        toml::Value::Array(
            crates
                .iter()
                .map(|c| toml::Value::String(format!("crates/{c}")))
                .collect(),
        ),
    );
    ws.remove("default-members");
    ws.remove("exclude");
    if let Some(deps) = ws
        .get_mut("dependencies")
        .and_then(toml::Value::as_table_mut)
    {
        deps.retain(|name, _| !name.starts_with("openreadout-") || crates.contains(name));
    }
    let body = toml::to_string(&doc)?;
    Ok(format!(
        "# Generated by `cargo xtask r-vendor` from the OpenReadout workspace manifest: the crates\n\
         # the R package needs. Do not edit; regenerate.\n{body}"
    ))
}

/// A crate manifest without its development-only sections.
fn crate_manifest(path: &Path) -> Result<String> {
    let mut doc: toml::Table = fs::read_to_string(path)?.parse()?;
    for key in ["dev-dependencies", "bench", "test", "example"] {
        doc.remove(key);
    }
    if let Some(targets) = doc.get_mut("target").and_then(toml::Value::as_table_mut) {
        for (_, t) in targets.iter_mut() {
            if let Some(t) = t.as_table_mut() {
                t.remove("dev-dependencies");
            }
        }
    }
    if let Some(pkg) = doc.get_mut("package").and_then(toml::Value::as_table_mut) {
        for key in ["autobenches", "autotests", "autoexamples"] {
            pkg.insert(key.into(), toml::Value::Boolean(false));
        }
        pkg.remove("readme");
    }
    Ok(toml::to_string(&doc)?)
}

fn copy_dir(from: &Path, to: &Path) -> Result<u64> {
    let mut bytes = 0;
    fs::create_dir_all(to)?;
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let src = entry.path();
        let dst = to.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            bytes += copy_dir(&src, &dst)?;
        } else {
            bytes += fs::copy(&src, &dst)?;
        }
    }
    Ok(bytes)
}

fn dir_size(p: &Path) -> u64 {
    fs::read_dir(p).map_or(0, |rd| {
        rd.flatten()
            .map(|e| {
                let path = e.path();
                if path.is_dir() {
                    dir_size(&path)
                } else {
                    e.metadata().map_or(0, |m| m.len())
                }
            })
            .sum()
    })
}

/// Drop tests, benches and examples of the vendored crates, and clear their checksum lists so
/// cargo does not look for the removed files (the package checksum stays).
fn prune_vendor(vendor: &Path) -> Result<()> {
    for entry in fs::read_dir(vendor)? {
        let dir = entry?.path();
        if !dir.is_dir() {
            continue;
        }
        // Keep what a manifest names explicitly (a [[bench]] or [[test]] path must exist).
        let manifest = fs::read_to_string(dir.join("Cargo.toml")).unwrap_or_default();
        for sub in ["tests", "benches", "examples"] {
            let p = dir.join(sub);
            let named = manifest.contains(&format!("path = \"{sub}/"));
            if p.is_dir() && !named {
                fs::remove_dir_all(&p)?;
            }
        }
        // winapi's GNU import libraries (100 MB): Rtools' MinGW has the same libraries, and the
        // Makevars build sets WINAPI_NO_BUNDLED_LIBRARIES so the crate links against those.
        let name = dir
            .file_name()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_default();
        if name.starts_with("winapi-")
            && name.contains("-pc-windows-gnu-")
            && dir.join("lib").is_dir()
        {
            fs::remove_dir_all(dir.join("lib"))?;
        }
        let ck = dir.join(".cargo-checksum.json");
        if ck.is_file() {
            let v: serde_json::Value = serde_json::from_str(&fs::read_to_string(&ck)?)?;
            let package = v.get("package").cloned().unwrap_or(serde_json::Value::Null);
            fs::write(
                &ck,
                serde_json::to_string(&serde_json::json!({ "files": {}, "package": package }))?,
            )?;
        }
    }
    Ok(())
}

pub fn vendor(root: &Path, out: Option<PathBuf>, keep_dir: bool) -> Result<()> {
    let pkg = root.join("r/openreadout");
    let dest = out.unwrap_or_else(|| pkg.join("src/rust"));
    if dest.exists() {
        fs::remove_dir_all(&dest).with_context(|| format!("removing {}", dest.display()))?;
    }
    fs::create_dir_all(dest.join("crates"))?;
    let crates = needed_crates(root)?;
    let mut src_bytes = 0;
    for c in &crates {
        let from = root.join("crates").join(c);
        let to = dest.join("crates").join(c);
        fs::create_dir_all(&to)?;
        fs::write(
            to.join("Cargo.toml"),
            crate_manifest(&from.join("Cargo.toml"))?,
        )?;
        src_bytes += copy_dir(&from.join("src"), &to.join("src"))?;
        if from.join("build.rs").is_file() {
            src_bytes += fs::copy(from.join("build.rs"), to.join("build.rs"))?;
        }
        for lic in ["LICENSE-MIT", "LICENSE-APACHE"] {
            if root.join(lic).is_file() {
                fs::copy(root.join(lic), to.join(lic))?;
            }
        }
    }
    fs::write(dest.join("Cargo.toml"), root_manifest(root, &crates)?)?;
    fs::copy(root.join("Cargo.lock"), dest.join("Cargo.lock"))?;

    let status = Command::new("cargo")
        .args(["vendor", "--versioned-dirs", "--manifest-path"])
        .arg(dest.join("Cargo.toml"))
        .arg(dest.join("vendor"))
        .stdout(std::process::Stdio::null())
        .status()
        .context("running cargo vendor")?;
    if !status.success() {
        bail!("cargo vendor failed");
    }
    prune_vendor(&dest.join("vendor"))?;
    fs::write(
        dest.join("vendor-config.toml"),
        "[source.crates-io]\nreplace-with = \"vendored-sources\"\n\n\
         [source.vendored-sources]\ndirectory = \"vendor\"\n",
    )?;
    let vendor_bytes = dir_size(&dest.join("vendor"));
    let status = Command::new("tar")
        .current_dir(&dest)
        .args(["-cJf", "vendor.tar.xz", "vendor"])
        .env("XZ_OPT", "-9")
        .status()
        .context("running tar (xz)")?;
    if !status.success() {
        bail!("tar -cJf failed");
    }
    if !keep_dir {
        fs::remove_dir_all(dest.join("vendor"))?;
    }
    let xz = fs::metadata(dest.join("vendor.tar.xz"))?.len();
    println!(
        "{}: {} workspace crates ({:.1} MB of source), vendored dependencies {:.1} MB -> vendor.tar.xz {:.1} MB",
        dest.display(),
        crates.len(),
        src_bytes as f64 / 1e6,
        vendor_bytes as f64 / 1e6,
        xz as f64 / 1e6
    );
    println!("next: R CMD build r/openreadout && R CMD check --as-cran openreadout_*.tar.gz");
    Ok(())
}
