---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  # bioconda recipe: integrations/bioconda (not yet submitted)
  - bioconda::openreadout=0.1.0
