#!/usr/bin/env python3
"""Check every relative link and fragment of the built docs site.

mdbook 0.5 has no link checker, and most pages include files from `docs/` whose relative links
were written for GitHub, so a link can be fine in the repository and broken on the site. Run
after `mdbook build book` (standard library only, Python 3.9+):

    python3 book/check_links.py            # checks book/book/
    python3 book/check_links.py OUT_DIR    # checks another build directory

For every page under the build directory it collects `href`/`src` attributes that are relative
(absolute URLs, `mailto:`, `data:` and `javascript:` are skipped), resolves them against the
page, and reports the link when the target file does not exist, when it resolves outside the
built site (e.g. `../../crates/…`, which works on GitHub but not on the published site), or when
its `#fragment` names no `id` in the target page. A link to a directory means its `index.html`.

Not checked: `print.html` (the same chapters concatenated, with links rewritten into its own
anchors), mdbook's own `404.html` (links are absolute to the site root) and `toc.html`, and the
`demo/` directory (the WebAssembly demo, built by a later CI step on pushes to main only).
Exit status: 0 when every link resolves (or is on the ALLOW list below), 1 otherwise.
"""
from __future__ import annotations

import os
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

BOOK_DIR = Path(__file__).resolve().parent
DEFAULT_OUT = BOOK_DIR / "book"

# Generated by mdbook, or not part of the book; see the module docstring.
SKIP_PAGES = {"print.html", "404.html", "toc.html"}
SKIP_DIRS = {"demo", "fonts", "css", "FontAwesome"}

# Known exceptions: (page, regular expression matched against the raw link, why it is fine).
ALLOW = [
    # The drop-a-file demo is copied into book/book/demo/ by the docs workflow's WebAssembly step,
    # which runs after the link check and only on pushes to main.
    ("getting-started/browser.html", r"^\.\./demo/", "demo page is built by a later CI step"),
]

SCHEME = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*:")
LINK_ATTRS = {"href", "src"}


class PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.ids: set[str] = set()
        self.links: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        for name, value in attrs:
            if value is None:
                continue
            if name == "id" or (tag == "a" and name == "name"):
                self.ids.add(value)
            elif name in LINK_ATTRS:
                self.links.append(value)

    handle_startendtag = handle_starttag


_cache: dict[Path, PageParser] = {}


def parse(path: Path) -> PageParser:
    if path not in _cache:
        parser = PageParser()
        parser.feed(path.read_text(encoding="utf-8", errors="replace"))
        _cache[path] = parser
    return _cache[path]


def allowed(page: str, link: str) -> bool:
    return any(page == p and re.search(rx, link) for p, rx, _ in ALLOW)


def check_link(out: Path, page: Path, link: str) -> str | None:
    """Return why `link` on `page` is broken, or None."""
    parts = urlsplit(link)
    path = unquote(parts.path)
    fragment = unquote(parts.fragment)
    if path.startswith("/"):
        return "absolute path (breaks under the site's base URL)"
    if path:
        target = Path(os.path.normpath(page.parent / path))
        try:
            target.relative_to(out)
        except ValueError:
            return "points outside the built site (a repository file? link to GitHub instead)"
        if target.is_dir():
            target = target / "index.html"
        if not target.exists():
            return "target does not exist"
    else:
        target = page
    if fragment and target.suffix == ".html":
        if fragment not in parse(target).ids:
            return f"no id '{fragment}' in {target.relative_to(out).as_posix()}"
    return None


def main() -> int:
    out = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_OUT
    if not (out / "index.html").exists():
        print(f"error: {out} has no index.html; run `mdbook build book` first", file=sys.stderr)
        return 1

    pages = []
    for root, dirs, files in os.walk(out):
        rel_root = Path(root).relative_to(out)
        if rel_root == Path("."):
            dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in files:
            if name.endswith(".html") and not (rel_root == Path(".") and name in SKIP_PAGES):
                pages.append(Path(root) / name)
    pages.sort()

    broken: list[tuple[str, str, str]] = []
    n_links = 0
    n_fragments = 0
    n_allowed = 0
    for page in pages:
        rel = page.relative_to(out).as_posix()
        for link in parse(page).links:
            link = link.strip()
            if not link or link.startswith("//") or SCHEME.match(link):
                continue
            n_links += 1
            n_fragments += "#" in link
            if allowed(rel, link):
                n_allowed += 1
                continue
            why = check_link(out, page, link)
            if why:
                broken.append((rel, link, why))

    for rel, link, why in broken:
        print(f"{rel}: {link}  ({why})")
    print(
        f"checked {n_links} relative links ({n_fragments} with a #fragment) on {len(pages)} pages: "
        f"{len(broken)} broken, {n_allowed} allowed by the ALLOW list",
        file=sys.stderr,
    )
    return 1 if broken else 0


if __name__ == "__main__":
    sys.exit(main())
