#!/usr/bin/env python3
"""Generate the JSON reference pages of the docs site from docs/schema/*.json.

The schemas are themselves generated from the Rust types (`cargo xtask schema gen`), so this
script turns the single source of truth into readable tables: one page per command payload,
one table per object type, with the field descriptions taken from the Rust doc comments.

Usage (from anywhere; standard library only, Python 3.9+):

    python3 book/gen_json_reference.py           # (re)write book/src/reference/json/*.md
    python3 book/gen_json_reference.py --check   # exit 1 if the committed pages are stale

The docs workflow regenerates the pages before `mdbook build`, so the published site always
matches the schemas on main even if a branch forgot to rerun this. To change a description,
edit the Rust doc comment, run `cargo xtask schema gen`, then this script.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "docs" / "schema"
OUT_DIR = ROOT / "book" / "src" / "reference" / "json"
REPO_BLOB = "https://github.com/openreadout/openreadout/blob/main/docs/schema"

# Page order and the command that produces each payload. `envelope` wraps all of them.
PAGES = [
    ("envelope", "every command with `--json`"),
    ("info", "`openreadout info FILE --json`"),
    ("info-format", "`openreadout info FILE --view format --json`"),
    ("info-full", "`openreadout info FILE --view full --json`"),
    ("info-explain", "`openreadout info FILE --view explain --json` (or `--ask QUESTION`)"),
    ("info-structure", "`openreadout info FILE --view structure --json`"),
    ("check", "`openreadout check FILE --json`"),
    ("check-planes", "`openreadout check FILE --planes --json`"),
    ("check-against", "`openreadout check A --against B --json` (also the MCP tool `openreadout_check` with `against`)"),
    ("check-report", "`openreadout check FILE --report --json` (the bundle itself is `report`; also the MCP tool `openreadout_check` with `report: true`)"),
    ("export", "`openreadout export FILE --json`"),
    ("export-attachment", "`openreadout export FILE --attachment NAME --json`"),
    ("spectra", "`openreadout spectra FILE --json` (`--ms-level`, `--polarity`, `--rt A-B`, `--precursor MZ`, `--charge`, `--count`)"),
    ("spectrum", "`openreadout spectra FILE --scan N --json` (or `--index I`, `--ms-level L --nth K`)"),
    ("table", "`openreadout table FILE --json` (FCS: `--compensate`, `--transform`, `--population`)"),
    ("trace", "`openreadout trace FILE --json`"),
    ("preview", "`openreadout preview FILE -o out.png --json`"),
    ("stats", "`openreadout stats FILE --json`"),
    ("stats-wells", "`openreadout stats PLATE --per well --json` (also the MCP tool `openreadout_stats` with `per: \"well\"`)"),
    ("chromatogram", "`openreadout analyze chromatogram FILE --json` (`--tic`, `--bpc`, `--mz M`, `--transition Q1>Q3`, `--trace N`)"),
    ("peaks", "`openreadout analyze peaks FILE --json` (`--rt T --window W`, `--integrate A-B`, `--targets LIST.csv`)"),
    ("assay", "`openreadout analyze assay wells|curve|dose-response|kinetics|growth|qc FILE --json`"),
    ("qpcr", "`openreadout analyze qpcr FILE --json` (`--cq`, `--ddcq`, `--standard-curve`)"),
    ("nmr-peaks", "`openreadout analyze nmr-peaks DIR_OR_FILE --json` (`--from auto|fid|processed`, `--integrate A:B`)"),
    ("ephys-features", "`openreadout analyze ephys-features FILE --json`"),
    ("spikes", "`openreadout analyze spikes FILE --trace N --json`"),
    ("gate", "`openreadout analyze gate FILE.fcs --workspace W.wsp --json` (or `--gatingml G.xml`)"),
    ("batch-table", "`openreadout batch MEASURE INPUTS… --json` and `openreadout stats|trace|table|info FILES… --tidy --json` (also `analyze gate`)"),
    ("batch-summary", "`openreadout batch summarize TABLE --by COLS --json`"),
    ("link", "`openreadout link PATH… --json`"),
    ("sidecar", "`openreadout info FILE --view full --sidecar --json`"),
    ("sidecar-file", "a `<file>.openreadout.json` sidecar written by `openreadout info --view full --sidecar`"),
    ("index", "`openreadout index DIR -o INDEX_DIR --json` (also `INDEX_DIR/index.json`)"),
    ("search", "`openreadout search INDEX_DIR QUERY --json`"),
    ("search-health", "`openreadout search INDEX_DIR --health --json`"),
    ("search-export", "`openreadout search INDEX_DIR QUERY --export OUT --json` (also `OUT/datasheet.json`)"),
    ("watch", "each line of `openreadout watch DIR` (also the `events[]` of the MCP tool `openreadout_watch`)"),
    ("formats", "`openreadout self formats --json`"),
    ("doctor", "`openreadout self doctor --json`"),
]

HEADER = "<!-- Generated by book/gen_json_reference.py from docs/schema/{name}.schema.json. Do not edit. -->\n\n"


def esc(text: str) -> str:
    """Make a description safe for a single Markdown table cell."""
    return " ".join(text.split()).replace("|", "|")


def anchor(name: str) -> str:
    return name.lower()


def type_of(node: object, defs: dict) -> str:
    """Render a schema node as a short, linked type expression."""
    if node is True or node == {}:
        return "any JSON"
    if not isinstance(node, dict):
        return "?"
    if "$ref" in node:
        name = node["$ref"].rsplit("/", 1)[-1]
        return f"[`{name}`](#{anchor(name)})"
    if "const" in node:
        return f'`"{node["const"]}"`' if isinstance(node["const"], str) else f"`{json.dumps(node['const'])}`"
    if "enum" in node:
        return " | ".join(f"`{json.dumps(v)}`" for v in node["enum"])
    for key in ("anyOf", "oneOf"):
        if key in node:
            parts = [type_of(v, defs) for v in node[key]]
            nullable = "`null`" in parts
            parts = [p for p in parts if p != "`null`"]
            out = " | ".join(parts)
            return f"{out} or `null`" if nullable else out
    t = node.get("type")
    if isinstance(t, list):
        non_null = [x for x in t if x != "null"]
        base = type_of({**node, "type": non_null[0]} if len(non_null) == 1 else {**node, "type": None}, defs)
        if len(non_null) > 1:
            base = " | ".join(f"`{x}`" for x in non_null)
        return f"{base} or `null`" if "null" in t else base
    if t == "array":
        items = type_of(node.get("items", True), defs)
        n_min, n_max = node.get("minItems"), node.get("maxItems")
        if n_min is not None and n_min == n_max:
            return f"array of {n_min} × {items}"
        return f"array of {items}"
    if t == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"object: string → {type_of(extra, defs)}"
        return "object"
    if t == "integer":
        fmt = node.get("format")
        return f"`integer` ({fmt})" if fmt else "`integer`"
    if t == "number":
        fmt = node.get("format")
        return f"`number` ({fmt})" if fmt else "`number`"
    if t:
        return f"`{t}`"
    return "any JSON"


def description(node: object, defs: dict) -> str:
    if not isinstance(node, dict):
        return ""
    if "description" in node:
        return node["description"]
    return ""


def object_table(node: dict, defs: dict) -> list[str]:
    props = node.get("properties", {})
    required = set(node.get("required", []))
    lines = ["| field | type | always present | description |", "| --- | --- | --- | --- |"]
    for name, sub in props.items():
        lines.append(
            f"| `{name}` | {type_of(sub, defs)} | {'yes' if name in required else ''} | {esc(description(sub, defs))} |"
        )
    return lines


def enum_table(node: dict) -> list[str] | None:
    if "enum" in node:
        return ["| value |", "| --- |"] + [f"| `{json.dumps(v)}` |" for v in node["enum"]]
    variants = node.get("oneOf") or node.get("anyOf")
    if variants and all(isinstance(v, dict) and "const" in v for v in variants):
        lines = ["| value | meaning |", "| --- | --- |"]
        lines += [f"| `{json.dumps(v['const'])}` | {esc(v.get('description', ''))} |" for v in variants]
        return lines
    return None


def render_def(name: str, node: dict, defs: dict, level: str = "###") -> list[str]:
    out = [f"{level} {name}", ""]
    if node.get("description"):
        out += [node["description"], ""]
    table = enum_table(node)
    if table is not None:
        out += table
    elif node.get("type") == "object" or "properties" in node:
        if node.get("properties"):
            out += object_table(node, defs)
        else:
            out += [f"Type: {type_of(node, defs)}."]
    else:
        out += [f"Type: {type_of(node, defs)}."]
    return out + [""]


def render_page(name: str, produced_by: str) -> str:
    schema = json.loads((SCHEMA_DIR / f"{name}.schema.json").read_text(encoding="utf-8"))
    defs = schema.get("$defs", {})
    title = schema.get("title", name)
    lines = [HEADER.format(name=name).rstrip("\n"), "", f"# {name}: `{title}`", ""]
    if name == "envelope":
        lines += [f"The wrapper around {produced_by}. The command's payload is `data` (on success) or `error` (on failure).", ""]
    else:
        lines += [f"The `data` payload of {produced_by}, inside the [envelope](envelope.md).", ""]
    if schema.get("description"):
        lines += [schema["description"], ""]
    lines += [
        f"JSON Schema: [`docs/schema/{name}.schema.json`]({REPO_BLOB}/{name}.schema.json) · "
        f"also printed by `openreadout self schema {name}`.",
        "",
        "## Fields",
        "",
    ]
    if schema.get("properties"):
        lines += object_table(schema, defs) + [""]
    else:
        lines += [f"Type: {type_of(schema, defs)}.", ""]
    if defs:
        lines += ["## Types", ""]
        for def_name, node in defs.items():
            lines += render_def(def_name, node, defs)
    return "\n".join(lines).rstrip() + "\n"


def render_index() -> str:
    lines = [
        "<!-- Generated by book/gen_json_reference.py. Do not edit. -->",
        "",
        "# JSON output",
        "",
        "One page per output shape, generated from the JSON Schemas in `docs/schema/`, which are "
        "generated from the code. Every command wraps its output in the same "
        "[envelope](envelope.md); [Reading the JSON output](../../getting-started/reading-json.md) "
        "explains it. Ignore fields you do not know: new fields can appear in any release, and "
        "`schema_version` changes only when a field is renamed, removed or retyped.",
        "",
        "| payload | produced by | root type |",
        "| --- | --- | --- |",
    ]
    for name, produced_by in PAGES:
        schema = json.loads((SCHEMA_DIR / f"{name}.schema.json").read_text(encoding="utf-8"))
        cell = produced_by.replace("|", "\\|")  # a literal `|` would end the table cell
        lines.append(f"| [{name}]({page_file(name)}) | {cell} | `{schema.get('title', name)}` |")
    return "\n".join(lines) + "\n"


def page_file(name: str) -> str:
    """The page of a payload (`index` would clash with this directory's own index.md)."""
    return "index-manifest.md" if name == "index" else f"{name}.md"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if generated pages differ from disk")
    args = ap.parse_args()

    known = {p.name.removesuffix(".schema.json") for p in SCHEMA_DIR.glob("*.schema.json")}
    missing = known - {n for n, _ in PAGES}
    if missing:
        print(f"error: schemas without a page in PAGES: {sorted(missing)}", file=sys.stderr)
        return 1

    pages = {"index.md": render_index()}
    for name, produced_by in PAGES:
        pages[page_file(name)] = render_page(name, produced_by)

    stale = []
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for fname, text in pages.items():
        path = OUT_DIR / fname
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(fname)
            if not args.check:
                path.write_text(text, encoding="utf-8")
    if args.check and stale:
        print(f"error: stale JSON reference pages: {stale}; run python3 book/gen_json_reference.py", file=sys.stderr)
        return 1
    print(f"{'checked' if args.check else 'wrote'} {len(pages)} pages in {OUT_DIR.relative_to(ROOT)}"
          + (f" ({len(stale)} updated)" if stale and not args.check else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
